name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Build&Test
        run: make release TAG=${GITHUB_SHA:0:12}

      - name: Cleanup
        if: ${{ failure() || cancelled() || always() }}
        run: make clean
