name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Build&Test
        run: make release TAG=${GITHUB_SHA:0:12}

      - name: Cleanup
        if: ${{ failure() || cancelled() || always() }}
        run: make clean

      - name: Deploy
        run: curl -s -X POST -H 'TOKEN:${{ secrets.DEPLOY_TOKEN }}' https://d.imega.ru -d "{\"namespace\":\"findbed\",\"project_name\":\"app\",\"tag\":\"${GITHUB_SHA:0:12}\"}"
